server.port=8000
spring.application.name=bionicpro-reports

spring.datasource.url=jdbc:ch:http://clickhouse:8123/olap_db
spring.datasource.username=airflow
spring.datasource.password=airflow
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

spring.data.jdbc.repositories.enabled=false
spring.data.jpa.repositories.enabled=false
spring.jpa.enabled=false

spring.datasource.initialize=false

spring.jdbc.template.query-timeout=30

logging.level.com.bionicpro.reports=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.apache.tomcat=WARN
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#keycloak.auth-server-url=http://keycloak:8080
#keycloak.realm=reports-realm
#keycloak.resource=reports-api
#keycloak.credentials.secret=oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
#keycloak.ssl-required=external
#keycloak.use-resource-role-mappings=true
#keycloak.bearer-only=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/reports-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs